/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circolariscuola;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Raoul Palummo
 */
public class JMColloqui extends javax.swing.JFrame {

    private ArrayList<Docente> albo = null;
    /**
     * Creates new form JMColloqui
     */
    public JMColloqui() {
        initComponents();
        
        Parser dom = new Parser();
        try {
            albo = (ArrayList<Docente>) dom.parseDocument("ricevimento.xml");
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(ValidateXML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(ValidateXML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ValidateXML.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TestoElenco = new javax.swing.JTextArea();
        TestoGiorno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BottoneGiorno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TestoProf = new javax.swing.JTextField();
        BottoneProf = new javax.swing.JButton();
        BottoneElenco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TestoElenco.setColumns(20);
        TestoElenco.setRows(5);
        jScrollPane1.setViewportView(TestoElenco);

        jLabel1.setText("Inserisci il giorno");

        BottoneGiorno.setText("Vai");
        BottoneGiorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneGiornoActionPerformed(evt);
            }
        });

        jLabel2.setText("Inserisci il prof");

        BottoneProf.setText("Vai");
        BottoneProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneProfActionPerformed(evt);
            }
        });

        BottoneElenco.setText("Visualizza tutti i prof");
        BottoneElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneElencoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TestoGiorno)
                            .addComponent(TestoProf, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BottoneGiorno)
                            .addComponent(BottoneProf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(BottoneElenco, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestoGiorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BottoneGiorno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TestoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BottoneProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(BottoneElenco))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneElencoActionPerformed
        TestoElenco.setText("");        
        for (Docente i:albo) {
            TestoElenco.append(i.toString()+"\n");
        }
    }//GEN-LAST:event_BottoneElencoActionPerformed

    private void BottoneGiornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneGiornoActionPerformed
         TestoElenco.setText("");
        String giorno=TestoGiorno.getText();
        for (Docente i:albo) {
            if(i.getGiorno().toLowerCase().equals(giorno.toLowerCase())){
                TestoElenco.append(i.toString()+"\n");
            }             
        }
    }//GEN-LAST:event_BottoneGiornoActionPerformed

    private void BottoneProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneProfActionPerformed
        TestoElenco.setText("");
        String nome=TestoProf.getText();
        for (Docente i:albo) {           
           if(i.getNome().toLowerCase().equals(nome.toLowerCase())){
               TestoElenco.append(i.toString()+"\n");
           }  
        }
    }//GEN-LAST:event_BottoneProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMColloqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMColloqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMColloqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMColloqui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMColloqui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottoneElenco;
    private javax.swing.JButton BottoneGiorno;
    private javax.swing.JButton BottoneProf;
    private javax.swing.JTextArea TestoElenco;
    private javax.swing.JTextField TestoGiorno;
    private javax.swing.JTextField TestoProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
